### ISSUE TITLE
Can't Run Codes on FE240hz Dataset

### ISSUE THREAD

**Issue by miaodd98** [Jee-King/CVPR2022_STNet#11]
Hello! I just follow the instructions on Readme for testing the codes on FE240hz Dataset. However, after doing all the right things, an error occurred and there is nowhere to fix it. Could you please check that for me? Many thanks!

(snn) PS D:\developing\CVPR2022_STNet-main> python .\test.py --config .\experiments\test\fe240\fe240.yaml
2023-07-28 17:21:18.475 | INFO     | __main__:<module>:63 - Load experiment configuration at: D:\developing\CVPR2022_STNet-main\experiments\test\fe240\fe240.yaml
2023-07-28 17:21:19.283 | INFO     | videoanalyst.model.module_base:update_params:60 - Load pretrained SiamTrack parameters from: snapshots/stnet/fe240.pkl whose md5sum is c457869c7b2be649e5ab69bd3608dbce
2023-07-28 17:21:19.324 | INFO     | videoanalyst.evaluation.event_benchmark.datasets.got10k:_get_cache_path:183 - GOT10k: passed cache file None invalid, change to default cache path
2023-07-28 17:21:19.331 | INFO     | videoanalyst.evaluation.event_benchmark.datasets.got10k:_build_cache_for_current_subset:202 - GOT10k: start loading subset val
  0%|                                                                                                                                                                                             | 0/48 [00:00<?, ?it/s] 
Traceback (most recent call last):
  File ".\test.py", line 77, in <module>
    tester.test()
  File "D:\developing\CVPR2022_STNet-main\videoanalyst\engine\tester\tester_impl\eventdata.py", line 63, in test
    experiment = ExperimentEVENT(root_dir,
  File "D:\developing\CVPR2022_STNet-main\videoanalyst\evaluation\event_benchmark\experiments\eventdata.py", line 47, in __init__
    self.dataset = GOT10k(root_dir, subset=subset, list_file=list_file)
  File "D:\developing\CVPR2022_STNet-main\videoanalyst\evaluation\event_benchmark\datasets\got10k.py", line 63, in __init__
    self._ensure_cache()
  File "D:\developing\CVPR2022_STNet-main\videoanalyst\evaluation\event_benchmark\datasets\got10k.py", line 161, in _ensure_cache
    self._build_cache_for_current_subset()
  File "D:\developing\CVPR2022_STNet-main\videoanalyst\evaluation\event_benchmark\datasets\got10k.py", line 206, in _build_cache_for_current_subset
    img_files, anno, meta = self.load_single_sequence(seq_dir)
  File "D:\developing\CVPR2022_STNet-main\videoanalyst\evaluation\event_benchmark\datasets\got10k.py", line 218, in load_single_sequence
    anno = np.loadtxt(os.path.join(seq_dir, "groundtruth_rect.txt"),
  File "C:\Users\miaod\Anaconda3\envs\snn\lib\site-packages\numpy\lib\npyio.py", line 1356, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
  File "C:\Users\miaod\Anaconda3\envs\snn\lib\site-packages\numpy\lib\npyio.py", line 999, in _read
    arr = _load_from_filelike(
ValueError: could not convert string '261.0772,104.5995,52.4504,103.5814' to float64 at row 0, column 1.

The ValueError looks so strange. My pytorch vision is 1.9.1+cu111. Is that having something to do with this issue?

**Comment by zhangxu155** [comment]
Hello，did you solve this problem？
